// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTnBSfvwg2oP_4KLiFKSzQzRmLUaatUmk',
    appId: '1:595666774474:web:99df527e3acdf1932b0733',
    messagingSenderId: '595666774474',
    projectId: 'skillswap-887cc',
    authDomain: 'skillswap-887cc.firebaseapp.com',
    storageBucket: 'skillswap-887cc.firebasestorage.app',
    measurementId: 'G-SHZ6VL1EK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJa4JGOsGwnZFR0sxfXFV0lQnWfB9YyKc',
    appId: '1:595666774474:android:7c647b389ceeb98d2b0733',
    messagingSenderId: '595666774474',
    projectId: 'skillswap-887cc',
    storageBucket: 'skillswap-887cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rexHYGNZEdaXORyFDO5Bp_RPPXtiwVg',
    appId: '1:595666774474:ios:2dbe17d5a6f968b12b0733',
    messagingSenderId: '595666774474',
    projectId: 'skillswap-887cc',
    storageBucket: 'skillswap-887cc.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rexHYGNZEdaXORyFDO5Bp_RPPXtiwVg',
    appId: '1:595666774474:ios:2dbe17d5a6f968b12b0733',
    messagingSenderId: '595666774474',
    projectId: 'skillswap-887cc',
    storageBucket: 'skillswap-887cc.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTnBSfvwg2oP_4KLiFKSzQzRmLUaatUmk',
    appId: '1:595666774474:web:10009a04cecb1cd12b0733',
    messagingSenderId: '595666774474',
    projectId: 'skillswap-887cc',
    authDomain: 'skillswap-887cc.firebaseapp.com',
    storageBucket: 'skillswap-887cc.firebasestorage.app',
    measurementId: 'G-6V5SSKFWX6',
  );
}
